/*
Propriété du 
Club Chinook/ETS
*/
/******************************************************************
					Global.h
******************************************************************/

#ifndef MOTOR_GLOBAL
#define MOTOR_GLOBAL
/******************************************************************
						Select module
******************************************************************/
//!!!!!!!!!!!!!!!!!!!!!!ALIM!!!!!!!!!!!!!!!!!!!
	//5V generated by firstSepic to power the actuators
//#define USE_ACTUATOR_ALIM	
	//Flyback control to Generate 5V onboard and
#define USE_LOGIC_ALIM	
	//12 generated by second Sepic to power sensors and bootstrap
#define USE_HV_ALIM

//!!!!!!!!!!!!!!!!!!!!!!MOTORS!!!!!!!!!!!!!!!!!
#define USE_QEI1
#define USE_TOWER_CONTROL
#define USE_ACTU
/******************************************************************
						Timing define
******************************************************************/
#define FOSC_MHZ 		100.0f  		//F en MHz (pas plus haut que 120Mhz)
#define FOSC			FOSC_MHZ*1000000.0f
#define BAUDRATE 		115200.0f  		//Baudrate of UART

#define FREQ_TMR3		2000.0f			//Refresh rate of alim control loop
#define FREQ_TMR5		8.0f			//Refrsh rate of motor control loop
#define FREQ_STEPPER	40E3f
#define FREQ_MAT		40E3f

#define TIMER3_FREQ     10.0f                           //Timeout freq
#define TIMER5_FREQ     0.1f                           //Timeout freq


/******************Memory*************/
#define NUM_OF_ECAN_BUFFERS 32

#define TEMPS_MS 100

/*****************DEBUGAGE************/
#define DEBUG_ADC 0
#define DEBUG_LEVIER 0
#define DEBUG_MSG_CAN_MANUAL_PITCH 0
#define DEBUG_MSG_CAN_BRAKE 0
#define DEBUG_MSG_CAN_CMD 0
/*************************************/

<<<<<<< HEAD
#define POT_PITCH_MAX 2.0f			//valeur maximale en volt que peu avoir le potentiomètre du pitch variable
#define POT_PITCH_MIN 0.8f			//valeur minimale en volt que peu avoir le potentiomètre du pitch variable
#define LEVIER_PITCH_NB_CRAN 32		//nombre cran mécanique sur le levier
=======
#define POT_PITCH_MAX 1.474f			//valeur maximale en volt que peu avoir le potentiomètre du pitch variable
#define POT_PITCH_MIN 0.387f			//valeur minimale en volt que peu avoir le potentiomètre du pitch variable
#define LEVIER_PITCH_NB_CRAN 14		//nombre cran mécanique sur le levier
>>>>>>> b240cbae2181adf246346eb01e3e7633fe858725

/******************************************************************
							IO
******************************************************************/
//#define LED1	_RA2
//#define LED2	_RA3
//#define LED3	_RA4
/**************************************************************
					Calculus Constant
***************************************************************/
//All const float are define in main
//Const should be define as extern

#define	MAT_COUNT_MAX 49000 //49*20*50

extern float Mat_Pos_Ref;
extern float Mat_Pos;

extern const float GM5;
#endif

